name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pylint
        pip install pytest
        pip install psycopg2
        pip install sql
        pip install django
        pip install django-widget-tweaks
        pip install pandas
        pip install tqdm
        pip install matplotlib
        pip install scikit-learn
        pip install protobuf==3.10.0
        pip install python-memcached==1.59
        pip install six==1.12.0
        pip install memcache
        pip install aiohttp
        pip install aiofiles
        pip install beautifulsoup4
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
