name: Pytest DZ3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        nohup python ./dz3/api_handler/api.py
    - name: Run pytest
      env:
        working-directory: ..
      run: | 
        python -m pytest ./dz3/tests/
        
