name: Pytest DZ8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install requests
        pip installprotobuf==3.10.0
        pip installpython-memcached==1.59
        pip installsix==1.12.0

    - name: Run pytest
      run: |
        py.test ./dz8/tests/test.py
